# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
    - run: curl https://raw.githubusercontent.com/davidkhala/go-utils/master/scripts/goCmd.sh | bash -s getAndEnsure github.com/davidkhala/chaincode release-1.4
    - run: cd nodejs; npm run build
      timeout-minutes: 15
    - run: cd nodejs; npm test
      timeout-minutes: 10
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
