name: Node.js CI

on: [ push, workflow_dispatch ]

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    env:
      IDCS_ID: ${{ secrets.IDCS_ID }}
      IDCS_PASSWORD: ${{ secrets.IDCS_PASSWORD }}
      GO111MODULE: on
    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - name: go get chaincode
        run: curl https://raw.githubusercontent.com/davidkhala/go-utils/master/scripts/goCmd.sh | bash -s get github.com/davidkhala/chaincode release-1.4
      - name: diagnose ensure (vendor)
        run: cd $(go env GOPATH)/src/github.com/davidkhala/chaincode/golang/diagnose; go mod vendor
      - run: cd nodejs; npm run build
        timeout-minutes: 30
      - run: cd nodejs; npm test
        timeout-minutes: 10
      - run: cd nodejs-rest; npm install
      - run: cd nodejs-rest; npm test
  windows:
    runs-on: windows-latest
    env:
      IDCS_ID: ${{ secrets.IDCS_ID }}
      IDCS_PASSWORD: ${{ secrets.IDCS_PASSWORD }}
      GO111MODULE: on
    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - run: cd nodejs; npm run build
        timeout-minutes: 30
      - name: go get chaincode
        run: |
          (Invoke-WebRequest "https://raw.githubusercontent.com/davidkhala/windows-utils/master/golang/goCmd.ps1").Content | Invoke-Expression
          Get-GO-Repos github.com/davidkhala/chaincode
      - name: diagnose ensure (vendor)
        run: cd $(go env GOPATH)/src/github.com/davidkhala/chaincode/golang/diagnose; go mod vendor
      - run: cd nodejs; npm run ping
      - run: cd nodejs; npm test
        timeout-minutes: 10
